CREATE TABLE XSGL_XLZXJL (
ID int(11) NOT NULL AUTO_INCREMENT COMMENT '主键',
XH varchar(64) NOT NULL COMMENT '学号',
XQ varchar(40) DEFAULT NULL COMMENT '学期',
LFZ varchar(20) DEFAULT NULL COMMENT '来访者',
XB varchar(2) DEFAULT NULL COMMENT '性别',
XZB varchar(40) DEFAULT NULL COMMENT '行政班',
ZXZ varchar(20) DEFAULT NULL COMMENT '咨询者',
ZXSJ datetime DEFAULT NULL COMMENT '咨询时间',
ZXNR varchar(255) DEFAULT NULL COMMENT '咨询内容',
PRIMARY KEY (ID)
) ENGINE=InnoDB AUTO_INCREMENT=7 DEFAULT CHARSET=utf8 COMMENT='心里咨询记录';