CREATE TABLE XSGL_XSLSKNBZ (
ID int(11) NOT NULL AUTO_INCREMENT COMMENT '主键',
XH varchar(64) NOT NULL COMMENT '学号',
BZSQRQ datetime DEFAULT NULL COMMENT '补助申请日期',
SQYY varchar(255) DEFAULT NULL COMMENT '申请原因',
BZJE double DEFAULT NULL COMMENT '补助金额',
FJ varchar(255) DEFAULT NULL COMMENT '附件',
SHZT varchar(20) DEFAULT NULL COMMENT '审核状态',
BZ varchar(255) DEFAULT NULL COMMENT '备注',
PRIMARY KEY (ID)
) ENGINE=InnoDB AUTO_INCREMENT=7 DEFAULT CHARSET=utf8 COMMENT='学生临时困难补助';