CREATE TABLE XSGL_XSZXJ (
ID int(11) NOT NULL AUTO_INCREMENT COMMENT '主键',
XH varchar(64) NOT NULL COMMENT '学号',
ZXJMC varchar(40) DEFAULT NULL COMMENT '助学金名称',
XQ varchar(40) DEFAULT NULL COMMENT '学期',
ZKBMH varchar(40) DEFAULT NULL COMMENT '中考报名号',
ZXJE double DEFAULT NULL COMMENT '助学金额',
SFRQ datetime DEFAULT NULL COMMENT '始发日期',
TFRQ datetime DEFAULT NULL COMMENT '停发日期',
TFYY varchar(40) DEFAULT NULL COMMENT '停发原因',
ZZDWHGR varchar(20) DEFAULT NULL COMMENT '资助单位或个人',
ZXJLX varchar(20) DEFAULT NULL COMMENT '助学金类型',
FJ varchar(255) DEFAULT NULL COMMENT '附件',
SHZT varchar(20) DEFAULT NULL COMMENT '审核状态',
BZ varchar(255) DEFAULT NULL COMMENT '备注',
PRIMARY KEY (ID)
) ENGINE=InnoDB AUTO_INCREMENT=7 DEFAULT CHARSET=utf8 COMMENT='学生助学金';