CREATE TABLE XSGL_XSJXJ (
ID int(11) NOT NULL AUTO_INCREMENT COMMENT '主键',
XH varchar(64) NOT NULL COMMENT '学号',
JXJMC varchar(40) DEFAULT NULL COMMENT '奖学金名称',
JXJBH varchar(64) DEFAULT NULL COMMENT '奖学金编号',
JXJDJ varchar(40) DEFAULT NULL COMMENT '奖学金等级',
JXJLX varchar(40) DEFAULT NULL COMMENT '奖学金类型',
JXJE double DEFAULT NULL COMMENT '奖学金额',
HJXQ varchar(40) DEFAULT NULL COMMENT '获奖学期',
HJRQ datetime DEFAULT NULL COMMENT '获奖日期',
ZZDWHGR varchar(40) DEFAULT NULL COMMENT '资助单位或个人',
JXJLY varchar(40) DEFAULT NULL COMMENT '奖学金来源',
FJ varchar(255) DEFAULT NULL COMMENT '附件',
SHZT varchar(5) DEFAULT NULL COMMENT '审核状态',
BZ varchar(255) DEFAULT NULL COMMENT '备注',
PRIMARY KEY (ID)
) ENGINE=InnoDB AUTO_INCREMENT=7 DEFAULT CHARSET=utf8 COMMENT='学生奖学金';