CREATE TABLE XSGL_XSQJD (
ID int(11) NOT NULL AUTO_INCREMENT COMMENT '主键',
XH varchar(64) NOT NULL COMMENT '学号',
QJLB varchar(20) DEFAULT NULL COMMENT '请假类别',
QJSY varchar(255) DEFAULT NULL COMMENT '请假事由',
KSSJ datetime DEFAULT NULL COMMENT '开始时间',
JSSJ datetime DEFAULT NULL COMMENT '结束时间',
QJZT varchar(20) DEFAULT NULL COMMENT '请假状态',
SFXJ varchar(2) DEFAULT NULL COMMENT '是否销假',
XJSJ datetime DEFAULT NULL COMMENT '销假时间',
BZ varchar(255) DEFAULT NULL COMMENT '备注',
FJ varchar(255) DEFAULT NULL COMMENT '附件',
PRIMARY KEY (ID)
) ENGINE=InnoDB AUTO_INCREMENT=7 DEFAULT CHARSET=utf8 COMMENT='学生请假单';