CREATE TABLE XSGL_ZBGLQXBM (
ID int(11) NOT NULL AUTO_INCREMENT COMMENT '主键',
XH varchar(64) NOT NULL COMMENT '学号',
BT varchar(40) DEFAULT NULL COMMENT '标题',
QJSY varchar(255) DEFAULT NULL COMMENT '请假事由',
ZBKSSJ datetime DEFAULT NULL COMMENT '值班开始时间',
ZBJSSJ datetime DEFAULT NULL COMMENT '值班结束时间',
ZDRQ datetime DEFAULT NULL COMMENT '制定日期',
ZDR varchar(20) DEFAULT NULL COMMENT '制定人',
SXZT varchar(20) DEFAULT NULL COMMENT '生效状态',
JG varchar(40) DEFAULT NULL COMMENT '机构',
ZBLX varchar(20) DEFAULT NULL COMMENT '值班类型',
GH varchar(64) DEFAULT NULL COMMENT '工号',
PRIMARY KEY (ID)
) ENGINE=InnoDB AUTO_INCREMENT=7 DEFAULT CHARSET=utf8 COMMENT='值班管理（全校/部门）';