CREATE TABLE XSGL_XSZSGL (
ID int(11) NOT NULL AUTO_INCREMENT COMMENT '主键',
XH varchar(64) NOT NULL COMMENT '学号',
XM varchar(20) DEFAULT NULL COMMENT '姓名',
XZB varchar(40) DEFAULT NULL COMMENT '行政班',
ZSMC varchar(40) DEFAULT NULL COMMENT '证书名称',
GZ varchar(40) DEFAULT NULL COMMENT '工种',
DJ varchar(40) DEFAULT NULL COMMENT '等级',
XXLY varchar(40) DEFAULT NULL COMMENT '信息来源',
FJ varchar(255) DEFAULT NULL COMMENT '附件',
PRIMARY KEY (ID)
) ENGINE=InnoDB AUTO_INCREMENT=7 DEFAULT CHARSET=utf8 COMMENT='学生证书管理';